version: "3.7"

services:
  mysql:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: 1sampai8
    volumes:
      - ./db/fix.sql:/docker-entrypoint-initdb.d/fix.sql
    restart: on-failure

  web_pentest:
    build: web_for_pentest
    environment:
      DB: mysql
      LDAP: auth
    ports:
      - 7070:80
    
  dvwa:
    build: vulnerable-dvwa/
    environment:
      DB: mysql
    ports:
      - 8080:80

  bwapp:
    build: bWAPP
    environment:
      DB: mysql
    ports:
      - 9090:80
      
  auth:
    image: mlan/openldap:1
    restart: unless-stopped
    volumes:
      - ./web_for_pentest/seed:/var/lib/openldap/seed